#!/usr/bin/env python3
"""Paper text part 2: Sections 4-6."""

BLOCKS = [
('h1', '4. Machine Learning for Battery State Estimation'),

('h2', '4.1 From filters to recurrent networks'),
('p',
 "SOC estimation remains the most mature BMS function, and the corpus shows how machine learning entered it. The early-corpus pattern pairs learning with classical state estimation: Gaussian process regression for pack-level SOC with native uncertainty quantification [[10.1016/j.energy.2020.118000]], and \u2014 most influentially \u2014 recurrent networks embedded in unscented Kalman filters, where the LSTM supplies a learned observation model and the filter supplies recursive correction [[10.1016/j.energy.2020.117664]]. Pure data-driven branches developed in parallel: support vector and ensemble regressors on engineered features benchmarked under automotive drive cycles [[10.3390/wevj12010038]], and simulation-informed training pipelines that substitute automotive-accurate simulated data for exhaustive cell testing [[10.1016/j.jpowsour.2020.229108]]. Reviews of this first generation conclude that deep-learning SOC estimation is accurate on well-sampled data but suffers from weak interpretability and inconsistent benchmarking [[10.1016/j.est.2022.104664]][[10.20517/jmi.2024.84]]."),

('p',
 "A second generation tuned network structure itself. Particle-swarm-optimized LSTM improved accuracy and current-noise robustness over vanilla recurrent baselines [[10.1016/j.energy.2021.121236]], and evolutionary-assisted CNN\u2013BiLSTM hybrids report sub-1% drive-cycle SOC errors [[10.1016/j.heliyon.2024.e35183]]. This optimization-augmented family illustrates a recurring pattern of the corpus: gains are real but modest, and the meta-heuristic component is tuned offline while adding training cost \u2014 an investment that only pays at deployment if the estimator\u2019s life is long. Robustness-oriented work addresses pack heterogeneity directly, jointly estimating pack SOC and cell inconsistency with balancing-aware formulations [[10.1109/access.2021.3068776]], large-format applications extend estimation to containerized energy-storage strings with relaxed sensing [[10.1016/j.jpowsour.2024.235609]], unified frameworks estimate SOH and SOC jointly from partial charging data [[10.1016/j.ensm.2022.06.053]], and comparative benchmarks weigh accuracy against the computational budget of electrified powertrains [[10.1016/j.est.2024.114281]][[10.1016/j.est.2024.111877]]."),

('p',
 "Two features of this cluster stand out against the rest of the corpus. First, it is the only function where classical estimation theory and machine learning have genuinely fused in published practice: the filter-embedded pattern [[10.1016/j.energy.2020.117664]] recurs across the five-year window in increasingly sophisticated forms, whereas health estimation and prognostics largely abandoned hybrid filtering after their Gaussian-process phase. Second, SOC papers report the corpus\u2019s most standardized evaluation \u2014 drive-cycle profiles at room temperature with RMSE or MAE in percent SOC \u2014 which makes their benchmarks legible even where the underlying datasets remain private. The cost of that legibility is convergence: with every paper evaluating on the same standard cycles, the marginal contribution of a new architecture is shrinking, and the cluster\u2019s research attention is shifting toward robustness conditions \u2014 noise, sensor faults, temperature, and aging shift \u2014 where the standard benchmarks are silent."),

('h2', '4.2 Hybrid and physics-informed estimation'),
('p',
 "The most substantive recent shift in SOC estimation is the move from purely learned estimators to hybrid schemes in which a filter, an equivalent-circuit model, or a physics prior constrains the learner. GA-optimized LSTM networks coupled with improved adaptive Kalman filtering reach low error under measurement noise that breaks pure-network estimators [[10.1016/j.apenergy.2024.123508]]; equivalent-circuit-informed ML on impedance features estimates SOC across temperatures [[10.1016/j.energy.2023.128461]]; and physics-informed recurrent structures embed battery dynamics directly into the network\u2019s training objective [[10.1109/jrfid.2022.3211841]]. These schemes trade engineering complexity for extrapolation behavior: because the physics component carries structure that does not need to be relearned, hybrid estimators degrade more gracefully outside their training envelope \u2014 the property that matters most onboard."),

('h2', '4.3 Critical assessment'),
('p',
 "The SOC literature of the corpus is accurate but inward-looking. Reported errors are now consistently below 1\u20132% SOC on the standard drive cycles, yet 13 of the 17 corpus SOC papers rest on laboratory-scale data and 12 on a single chemistry under curated profiles, and only one demonstrates fleet-scale operation [[10.1016/j.jpowsour.2024.235609]]. The review literature itself identifies the consequence: benchmark heterogeneity makes cross-paper comparison nearly meaningless, and generalization across temperature, chemistry, and aging state remains weakly evidenced [[10.1016/j.egyai.2025.100585]]. The SOC function is, in other words, an area where the research problem has largely been solved on laboratory terms but the deployment problem \u2014 guaranteed accuracy on arbitrary packs over full aging \u2014 has not."),

('p',
 "State estimation is also where the corpus\u2019s two sensing-hardware threads meet the software thread. Impedance-based SOC estimation demonstrates that electrochemical information beyond terminal voltage can drive estimation when EIS is available [[10.1016/j.energy.2023.128461]], while the ultrasonic-sensing line proposes non-electrical channels that could in principle be integrated into pack hardware at automotive cost [[10.1016/j.egyai.2022.100188]]. Both remain laboratory-bound for cost and durability reasons, but they mark the boundaries of a design space \u2014 better software on existing sensors versus new sensors for better software \u2014 that the wider BMS industry is actively exploring."),

('h1', '5. Machine Learning for Health Estimation and Prognostics'),

('h2', '5.1 Feature engineering and classical estimators'),
('p',
 "SOH estimation and RUL prediction form the largest functional block of the corpus (35 papers). The founding pattern is classical: extract health-sensitive features from partial charge or discharge curves, then regress with Gaussian process or similar shallow models. Incremental-capacity analysis with Gaussian process regression established the template with explicit uncertainty bounds [[10.1016/j.energy.2019.116467]]; differential thermal voltammetry extended the feature space to thermal signatures [[10.1109/tte.2020.3028784]]; and deep Gaussian processes coupled capacity prognosis with degradation-mode identification [[10.1016/j.jpowsour.2019.227281]]. Relaxations of the measurement burden followed: random partial charging data proved sufficient for accurate SOH [[10.1109/tpel.2021.3134701]], and charging-segment adjustment refined features for vehicle-level use [[10.1016/j.apenergy.2024.124077]]. The landmark systematization of this generation is the 179-cell machine-learning pipeline of Roman et al., which showed that relaxed charge-curve features support accurate, uncertainty-quantified SOH estimation across a heterogeneous commercial-cell fleet [[10.1038/s42256-021-00312-3]]."),

('p',
 "The feature taxonomy underlying this generation is worth making explicit because it explains both the cluster\u2019s strengths and its brittleness. Incremental capacity and differential voltage features transform charge curves into peaks whose positions and areas track degradation mechanisms; differential thermal voltammetry adds the temperature dimension; and partial-charging features deliberately sacrifice completeness for practicality, accepting any sufficiently informative voltage window. The approach assumes that the feature-to-health mapping is stable across the cells used for training \u2014 an assumption that holds within a cell model and laboratory but weakens across manufacturers, formats, and field profiles. The 179-cell pipeline study is important precisely because it tested that assumption at fleet scale within one commercial technology, and its success should not be over-read as license to transfer features across technologies [[10.1038/s42256-021-00312-3]]."),

('h2', '5.2 Deep sequence and cross-cell models'),
('p',
 "Deep architectures entered prognostics as sequence models over capacity-fade trajectories and as representation learners over raw curves. Graph convolutional networks fuse multiple health indicators for joint SOH/RUL prediction [[10.1016/j.ress.2022.108947]]; BiLSTM\u2013Transformer hybrids track health under the specific stress of fast charging [[10.1016/j.energy.2024.133418]]; hybrid-fusion networks target real-time prediction streams [[10.1016/j.energy.2025.136618]]; graph neural networks over partial discharge curves improve cross-cell generalization [[10.1016/j.est.2024.113502]], and interpretable deep learning couples accuracy with transparency mechanisms [[10.1016/j.apenergy.2024.124713]]. A particularly important line uses real-world vehicle data rather than laboratory cycling, demonstrating that deep estimators can absorb field-data noise [[10.1016/j.energy.2023.126855]], and pack-level fusion methods now estimate SOH directly from fleet charge streams [[10.1016/j.geits.2024.100169]]. At the field\u2019s high end, a Nature Communications study showed that deep models can estimate SOH without additional degradation experiments by learning trajectory features that generalize across chemistries [[10.1038/s41467-023-38458-w]]."),

('h2', '5.3 Early-life prediction'),
('p',
 "Early-life prediction \u2014 forecasting lifetime from the first cycles \u2014 is the corpus\u2019s most consequential methodological export to practice, because it compresses test times from months to days. Beyond the founding study [[10.1038/s41560-019-0356-8]], charge-process features predict cycle life across diverse duty cycles [[10.1016/j.apenergy.2021.116897]], ML frameworks extract lifetime information from formation-style tests [[10.1016/j.energy.2021.120205]], hybrid physics-plus-learned models give early RUL from limited cycles [[10.1016/j.jclepro.2021.128265]], and discharge-voltage features extend the approach to lithium-metal chemistries [[10.1002/advs.202402608]]. Board-level implementations close the loop to hardware, predicting capacity and RUL on embedded platforms in real time [[10.1016/j.est.2022.104901]]."),

('p',
 "The economics of early-life prediction explain its rapid uptake: formation and initial cycling are already performed on every production cell, so early-prediction features are available for free at the point of manufacture, and warranty structuring, second-life triage, and cell matching all become data products. The methodological caveat is selection: cells that reach the secondary market, and cell batches that survive manufacturing screens, are conditioned samples whose early-cycle feature distributions differ from the training population. No corpus paper yet quantifies this survivorship effect, which makes it one of the more consequential open measurement problems in the cluster."),

('h2', '5.4 Physics-informed and hybrid prognostics'),
('p',
 "The prognostics cluster shows the corpus\u2019s most visible physics-informed turn. Physics-informed online degradation models support proactive health management by embedding degradation structure into learned models [[10.1016/j.ymssp.2022.109347]]; physics-informed hybrid reinforcement learning reduces the data demand of SOH estimation [[10.1038/s41598-025-30602-4]]; a generalizable PINN achieves cross-cell SOH estimation from limited early-cycle data [[10.1016/j.jechem.2025.08.093]]; EIS-informed physics-constrained networks estimate SOH from small impedance datasets [[10.1016/j.energy.2025.139753]]; and a generic physics-informed framework predicts RUL from small early-life samples across datasets [[10.1016/j.apenergy.2025.125314]]. Multi-feature hybrid schemes lift RUL accuracy across datasets [[10.1016/j.est.2025.118415]], signal-decomposition hybrids sharpen capacity-fade prediction on noisy series [[10.1038/s41598-025-92262-8]], and deep reinforcement learning adaptively selects prognostic models along aging trajectories [[10.1016/j.ress.2025.111392]]. The shared motivation is clear: pure data-driven models extrapolate poorly past their training envelope, and physics priors are the cheapest available source of structure."),

('h2', '5.5 Transfer learning and cross-domain generalization'),
('p',
 "Transfer learning addresses the corpus\u2019s central weakness \u2014 generalization \u2014 directly. Domain-adversarial training adapts SOH estimators across operating conditions without target-domain labels [[10.1109/tpel.2021.3117788]]; deep transfer learning with partial charging curves carries capacity estimation across cell types [[10.1016/j.energy.2023.127033]]; transfer under fast-charging protocols extends the approach to protocol shift [[10.1016/j.isci.2025.112235]]; transfer-learning-based EIS estimation crosses chemistries [[10.1109/tte.2025.3533540]]; and a general framework quantifies and manages the laboratory-to-fleet domain gap for trained estimators [[10.1016/j.apenergy.2024.125086]]. Framework-level work consolidates these threads: real-time online feature extraction from vehicle data [[10.1016/j.jpowsour.2025.236784]] and reviews charting non-probabilistic estimation techniques [[10.1016/j.apenergy.2021.117346]], alongside joint SOH/RUL architectures that fuse multiple health indicators [[10.1016/j.ress.2022.108947]]."),

('h2', '5.6 Critical assessment'),
('p',
 "Prognostics is where the corpus\u2019s validation problem bites hardest. Accuracy claims cluster around SOH errors of 1\u20132% and RUL errors of tens of cycles, but these are established overwhelmingly on public benchmark cells: the Severson-MATR dataset alone appears in 11 corpus papers, NASA and CALCE in 12 more. Within-cell splits and k-fold protocols \u2014 which leak trajectory information between train and test \u2014 account for 10 of the 35 primary studies in the health-prognostics complex, and for 17 of the corpus as a whole. The transfer-learning papers are the honest exception, in that their whole object is distribution shift; but they also reveal how much shift remains unaddressed, with negative transfer cases and per-protocol fine-tuning acknowledged but rarely resolved. The mature judgment is that SOH estimation under controlled conditions is approaching incremental returns, while the prognostics problem that matters \u2014 calibrated lifetime and safety margins for arbitrary packs in the field \u2014 remains open [[10.1016/j.joule.2019.11.018]][[10.1016/j.jechem.2023.03.026]]."),

('p',
 "Metric heterogeneity compounds the validation problem. SOH papers report RMSE or MAE in percent capacity, sometimes normalized differently; RUL papers report cycle counts, percentages of true life, or knee-point errors defined against arbitrary end-of-life thresholds; charging papers report charge time, energy efficiency, and capacity retention after fixed cycle counts, which conflate estimation error with protocol quality. No two clusters share a metric, and within clusters the definitions vary enough that a quantitative meta-analysis of pooled accuracy \u2014 the trademark move of clinical meta-research \u2014 is not defensible for this literature. The qualitative synthesis of Sections 4\u20138 is therefore organized around method families, data regimes, and validation designs rather than around pooled effect sizes; this is a deliberate methodological choice, and readers should treat any cross-paper accuracy table with corresponding caution."),

('h1', '6. Machine Learning for Charging Control and Optimization'),

('h2', '6.1 Closed-loop optimization of charging protocols'),
('p',
 "Charging control is the function where machine learning has changed experimental practice most directly, not merely what can be estimated. The defining result is Attia et al.: a Bayesian optimization loop over charging-protocol parameters, evaluating candidate protocols through continuous cycling, identified protocols charging cells to 80% in around 10 minutes within 2.5 months \u2014 against roughly 18 months for the equivalent manual search [[10.1038/s41586-020-1994-5]]. The significance is methodological as much as practical: closed-loop learning converts protocol design from expert iteration into sample-efficient optimization. Subsequent work broadened the objective space. Ensemble surrogate models make model-based charging-strategy optimization tractable under multi-objective trade-offs [[10.1016/j.enconman.2025.120170]], and data-driven Bayesian fast-charging optimization reduces charge time under explicit degradation constraints [[10.1109/tte.2023.3311813]]."),

('h2', '6.2 Learning to charge around degradation physics'),
('p',
 "A second line embeds degradation mechanisms into the charging decision itself. Machine-learning fast charging that perceives and regulates internal lithium-plating onset enables plating-free rapid protocols that violate conventional voltage-safe schedules with impunity [[10.1016/j.ensm.2022.12.034]]. Adaptive multistage constant-current schemes adjust stage boundaries online against measured degradation [[10.1016/j.renene.2019.08.077]], and module-level optimization manages temperature gradients across packs during charging [[10.1016/j.energy.2022.126331]]. Pack-level extensions coordinate balance-aware charging for imbalanced strings [[10.1016/j.est.2024.111755]] and multi-objective meta-heuristic schemes negotiate charge time against temperature rise and aging [[10.1016/j.est.2024.112046]]."),

('p',
 "Scale effects are the cluster\u2019s frontier. Cell-level protocols do not compose into pack-level schedules, because cell-to-cell variability makes the weakest cell the binding constraint; module-level optimization with temperature-gradient constraints [[10.1016/j.energy.2022.126331]] and balance-aware pack charging [[10.1016/j.est.2024.111755]] are the corpus\u2019s first responses. The control-theoretic gap is equally important: optimization produces open-loop schedules, while deployment wants closed-loop policies that react to measured state \u2014 which is precisely where the reinforcement-learning line, still under-represented in journal-grade hardware validation, is expected to grow."),

('h2', '6.3 Critical assessment'),
('p',
 "Charging is also where the gap between demonstration and deployment is most concrete. The corpus contains eight charging papers; of these, one is a large-scale closed-loop hardware campaign [[10.1038/s41586-020-1994-5]], three validate on laboratory hardware, and the remainder are simulation-only or optimization-method demonstrations. RL-based charging strategies \u2014 a substantial adjacent literature \u2014 are underrepresented here precisely because most are validated in simulation against electrochemical models. The unsolved problem is certifiable learning-based charging: a controller that adapts to cell-to-cell variability and aging in production vehicles must carry a safety argument that current model-free learners cannot yet make, which is why mechanism-aware schemes such as plating-perception control [[10.1016/j.ensm.2022.12.034]] are the most deployment-relevant results in this cluster."),

('tbl', 'TABLE3'),
]
