#!/usr/bin/env python3
"""Condensed TTE-submission text (12-page limit): part 3."""
import paper_part3 as FULL

TABLES = {
    'TABLE_METH': FULL.TABLE_METH,
    'TABLE2': FULL.TABLE2,
    'TABLE_VALID': FULL.TABLE_VALID,
    'TABLE_DATASETS': FULL.TABLE_DATASETS,
    'TABLE_CONF': FULL.TABLE_CONF,
    'TABLE_REP': FULL.TABLE3,
    'TABLE_LLM': FULL.TABLE_LLM,
    'TABLE_CHECKLIST': FULL.TABLE_CHECKLIST,
}

BLOCKS = [
('h1', '8. Cross-Cutting Directions'),

('h2', '8.1 Physics-informed learning, interpretability, and uncertainty'),
('p',
 "Physics-informed and hybrid model\u2013data learning is the corpus's largest methodological theme (24 papers across all functions) \u2014 in state estimation [[10.1109/jrfid.2022.3211841]][[10.1016/j.measurement.2025.118985]], heat-generation estimation [[10.1016/j.jechem.2022.11.036]], prognostics [[10.1016/j.ymssp.2022.109347]], and impedance-based diagnostics [[10.1016/j.rser.2023.113807]], with physics-constrained autoencoders improving health prediction over purely learned counterparts [[10.1007/s00521-022-07291-5]] and a physical-plus-data-driven fusion literature for internal-state estimation [[10.3390/batteries10120442]]. The caution is that most physics-informed studies embed simplified physics \u2014 equivalent-circuit or reduced electrochemical models \u2014 so the hybrid inherits model bias even as it gains structure, and its validation is no stronger than that of purely data-driven peers (Section 3.4). A smaller but consequential cluster makes learning systems inspectable: explainability-driven feature selection improves estimator robustness [[10.1016/j.ress.2022.109046]], interpretable ML links manufacturing coating parameters to cell capacity [[10.1016/j.conengprac.2022.105202]], interpretable hybrid ML untangles degradation chemistries in lithium\u2013sulfur cells [[10.1002/anie.202214037]], and uncertainty-aware models deliver calibrated early-life predictions [[10.1039/d2dd00067a]]. For safety cases only calibrated uncertainty has a route into certification; attribution supports debugging."),

('h2', '8.2 Digital twins, cloud BMS, and new sensing'),
('p',
 "System-level architecture is emerging as a research object: digital twins track individual battery aging through incremental learning [[10.1016/j.eswa.2023.120444]] and couple LSTM surrogates with real-time thermal observation [[10.1016/j.est.2023.107203]]; cloud platforms perform in-situ life prediction at fleet scale [[10.1016/j.ensm.2023.02.035]]; second-life workflows use impedance-based accelerated SOH estimation to triage retired packs [[10.1016/j.est.2022.106295]], and learned battery models with numerical search estimate real-time state-of-power [[10.1016/j.est.2026.123023]]. Non-electrical sensing broadens the measurement base \u2014 ultrasonic signatures provide a SOC channel orthogonal to voltage sensing [[10.1016/j.egyai.2022.100188]] \u2014 and ML mappings from equivalent-circuit parameters to electrochemical properties give classical BMS models a physically interpretable learned layer [[10.1016/j.est.2024.113257]]. These settings differ in latency budgets, error tolerance, and update cadence, and the field is beginning to design for those differences. Production-side mapping [[10.1002/batt.202300046]], coating interpretability [[10.1016/j.conengprac.2022.105202]], and defect detection [[10.1016/j.jechem.2025.04.025]] complete the picture: cell quality is itself a BMS input."),

('h2', '8.3 Foundation models and LLM-based management'),
('p',
 "The corpus's youngest theme is generative: domain-specific LLMs perform risk analysis of battery energy-storage incidents [[10.1016/j.ress.2026.112416]], and knowledge-enhanced LLM agents orchestrate vehicle-cloud battery management [[10.1016/j.ensm.2026.104983]]. Because BMS software is safety-critical, this review positions foundation models not as better estimators but as orchestration layers, and Table VII makes the division of labor explicit: the right-hand guardrails are normative guidance proposed here, not claims about the published studies. Two entries deserve emphasis. Failure mode: an estimator's error is a bounded number, while an LLM's failure is open-ended hallucinated text \u2014 so LLM outputs must be restricted to structured, checkable forms and never feed protection logic as free text. Safety authority: LLM components must never hold direct cell-level protection authority; that role belongs to physics-based envelopes and calibrated estimators whose uncertainty is quantified."),

('tbl', 'TABLE_LLM'),

('h1', '9. Research Gaps, Reporting Standards, and Future Directions'),
('p',
 "Cross-referencing the bibliometric analysis of Section 3 with the function-level reviews yields six structural gaps. (1) Validation practice: 17 primary studies use within-cell or unsupervised k-fold validation, and only 9 of all 103 demonstrate online or fleet use; standardized cross-cell, cross-chemistry, and lab-to-fleet transfer protocols should become reporting norms, as already practiced by the transfer-learning and general-framework studies [[10.1016/j.apenergy.2024.125086]][[10.1109/tte.2025.3533540]]. (2) Data monoculture: a single public dataset underlies 11 studies, NASA and CALCE sustain much of the rest, and 36 papers use private laboratory cells; federated learning over fleets, anonymized fleet-data releases, and multi-institution cycling campaigns \u2014 in the spirit of the 179-cell pipeline [[10.1038/s42256-021-00312-3]] \u2014 would diversify the evidence base, and papers should at minimum disclose split definitions, seeds, and compute budgets. (3) Edge deployment: only isolated works treat onboard compute, memory, and latency as first-class constraints [[10.1016/j.est.2022.104901]][[10.1016/j.jpowsour.2025.236784]]; quantization-aware training, resource-constrained architecture search, and cloud\u2013edge hybrid designs are the natural research program. (4) Trust: uncertainty must be calibrated rather than post-hoc [[10.1039/d2dd00067a]], interpretability must bound behavior rather than merely attribute it, and hybrid physics\u2013data architectures are the most credible certification path because part of their behavior is analytically specified. (5) Foundation-model integration: the first LLM studies [[10.1016/j.ress.2026.112416]][[10.1016/j.ensm.2026.104983]] suggest a division of labor \u2014 foundation models for reasoning and orchestration, conventional ML for calibrated estimation, physics models for safety envelopes \u2014 that should be formalized with grounding and latency guarantees. (6) Under-served functions: balancing is nearly untouched beyond pack-level insight [[10.1016/j.est.2023.106931]], charging needs certifiable adaptive protocols, and thermal management remains simulation-dominated [[10.1016/j.est.2023.106688]]; these are control problems where errors act on the battery, so closing them requires the safety-case machinery of gap 4 as much as new algorithms."),

('h2', '9.1 A reporting checklist for machine-learning BMS studies'),
('p',
 "The most concrete artifact this review can offer is procedural. Modeled on the CONSORT and PRISMA checklists, Table IX proposes a twelve-item BMS-ML reporting checklist (BMS-ML-RC): the minimum metadata a study should disclose for its accuracy claims to be comparable, reproducible, and poolable. Each item corresponds to a practice whose absence the corpus analysis showed to be distorting \u2014 undisclosed splits, uncalibrated uncertainty, unnamed datasets, unquantified compute. We suggest journals adopt it as a submission checklist and that authors attach it to their released datasets."),

('tbl', 'TABLE_CHECKLIST'),

('h1', '10. Conclusion'),
('p',
 "This review has examined AI-powered battery management through a verified 103-study corpus extended by a 14-paper conference sensitivity analysis. Three conclusions stand out. First, the field has undergone a marked methodological evolution: classical feature-based learners gave way to deep sequence models, now being displaced at the frontier by physics-informed hybrids, optimization-augmented learning, transfer-learning regimes, and foundation-model components. Second, the center of gravity remains estimation (state, health, lifetime), where learning systems have largely succeeded on laboratory terms; control functions (charging, thermal, balancing) remain demonstrably transformable but under-evidenced for deployment. Third, published accuracy progress is not matched by validation progress: online or fleet-level demonstration appears in fewer than one study in ten, benchmark monoculture distorts the apparent state of the art, and the field's favored remedy \u2014 physics-informed architecture \u2014 does not substitute for validation rigor (54% versus 73% strong-protocol validation). The near-term agenda follows directly: standardized cross-domain validation protocols, diversified fleet data, edge-deployable architectures, calibrated uncertainty as a certification prerequisite, and a principled division of labor between foundation models, calibrated estimators, and physics-based safety envelopes. If the last five years were about discovering what machine learning can estimate about a battery, the next five will be decided by what it can be trusted to do \u2014 onboard, at fleet scale, across chemistries, and over full cell lifetimes."),
]
