#!/usr/bin/env python3
"""Paper text: ML in battery management — blocks consumed by build_docx.py.
Citations use [[doi]] placeholders resolved to numbered [n] at build time."""

TITLE = "Machine learning in battery management systems: a structured scoping review and classification of 103 peer-reviewed studies, 2019\u20132026"

AUTHOR_LINES = [("Hussain Touhid Siddiquee", "Leading University, Sylhet, Bangladesh"),
                ("Syeda Salsabil Islam Ariya", "Leading University, Sylhet, Bangladesh"),
                ("Jasimul Islam Chowdhury", "Leading University, Sylhet, Bangladesh")]

ABSTRACT = [
 "Machine learning (ML) has moved from a promising addition to battery research to a load-bearing component of modern battery management systems (BMS). This paper presents a structured scoping review of 103 peer-reviewed journal articles published between 2019 and 2026 that apply machine learning to battery management tasks, assembled from a Crossref-verified pool of peer-reviewed journal articles and classified uniformly by management function, method family, chemistry, data source, and validation practice. The corpus is classified by management function (state of charge, state of health, remaining useful life, charging control, thermal management, fault and safety, and cross-cutting themes), by method family, by battery chemistry, by data source, and by validation practice.",

 "The bibliometric analysis reveals a clear five-year evolution. Classical shallow learners such as Gaussian process regression and support vector machines dominated the early window, contributing 11 of the 23 corpus papers published from 2019 through 2021, with deep recurrent architectures rising sharply in 2022\u20132023. From 2022 onward, physics-informed and hybrid model\u2013data approaches became one of the fastest-growing families, reaching 24 of 103 corpus papers, while optimization-augmented learning and transfer learning together account for a further 16 papers. The first large-language-model-based battery management studies appear in 2025\u20132026. Health estimation and prognostics remain the largest application cluster (35 papers), followed by the cross-cutting cluster (24), state estimation (17), fault and safety (9), charging control (8), and thermal management (8).",

 "Three structural weaknesses persist across the five-year window. First, validation practice is heterogeneous and often weak: only 9 of 103 studies demonstrate their estimators on real vehicle or fleet data, while 17 rely on within-cell or k-fold splits that overstate generalization. Second, benchmark-data dependence is high but narrow; the Severson/Toyota, NASA, and CALCE datasets recur across ostensibly independent studies, inflating apparent comparability. Third, the laboratory-to-field gap remains the field\u2019s defining challenge: sub-percent accuracy claims rarely survive chemistry, temperature, and current-profile shifts, and onboard compute constraints are discussed in a minority of works. The review\u2019s sharpest finding is that physics-informed architectures, often assumed to improve reliability by construction, are validated less rigorously than purely data-driven peers (54% versus 73% strong-protocol share): physics priors reduce data demand but do not substitute for rigorous out-of-distribution testing. The review closes with a research agenda prioritizing cross-domain validation standards, uncertainty-aware and interpretable models, edge-deployable architectures, and the safe integration of foundation models into safety-critical BMS software.",
]

KEYWORDS = ("machine learning; battery management systems; lithium-ion batteries; state of charge; "
            "state of health; remaining useful life; deep learning; physics-informed neural networks; "
            "transfer learning; battery safety")

BLOCKS = [
('h1', '1. Introduction'),

('h2', '1.1 Electrification and the battery management problem'),
('p',
 "Lithium-ion batteries now anchor three converging transitions: the electrification of road transport, the proliferation of stationary storage in renewable-heavy grids, and the electrification of aerospace, marine, and industrial systems. In each of these settings, the battery is not a passive component but an actively managed asset whose usable capacity, lifetime, and safety depend on operating decisions made in real time. The battery management system is the embedded cyber-physical layer that makes those decisions: it senses cell voltages, currents, and temperatures; estimates unobservable internal states; protects against over-charge, over-discharge, and thermal abuse; balances cells; and increasingly negotiates charging strategies with the surrounding power system [[10.1038/s42256-020-0156-7]]."),

('p',
 "The difficulty of the management problem stems from the fact that the quantities that matter most \u2014 state of charge (SOC), state of health (SOH), internal temperature, and the onset of degradation or fault mechanisms \u2014 are not directly measurable. They must be inferred from noisy, partially observable terminal measurements under widely varying operating conditions. Model-based approaches built on equivalent-circuit or electrochemical models have served the industry well, but they face a persistent trade-off between fidelity and computational tractability, and their parameters drift as cells age [[10.1016/j.joule.2019.11.018]]. It is in this inference-and-decision layer that machine learning has made its most forceful entry."),

('h2', '1.2 The rise of machine learning in battery management'),
('p',
 "Machine learning entered battery management through estimation. Early applications treated SOC and SOH estimation as supervised regression on hand-engineered features, using support vector machines, Gaussian process regression, and shallow neural networks. Two studies then reset expectations for the whole field. Severson and colleagues showed that the entire cycle life of a lithium-ion cell could be predicted with a median test error near 9% using only features extracted from the first hundred cycles, on a public dataset of 124 cells [[10.1038/s41560-019-0356-8]]. Attia and colleagues demonstrated closed-loop Bayesian optimization of fast-charging protocols, identifying high-quality protocols in 2.5 months rather than the 18 months typical of manual experimentation [[10.1038/s41586-020-1994-5]]. Together these results reframed battery management as a data problem in which learning systems could outperform hand-tuned models both in estimation accuracy and in experiment efficiency."),

('p',
 "The five years that followed produced a wave of published applications across every BMS function: recurrent and convolutional networks for SOC and SOH [[10.1016/j.energy.2020.117664]][[10.1016/j.energy.2023.126855]], graph and transformer architectures for prognostics [[10.1016/j.ress.2022.108947]][[10.1016/j.energy.2024.133418]], physics-informed neural networks that embed electrochemical and thermal priors into learning systems [[10.1016/j.jechem.2022.11.036]][[10.1109/jrfid.2022.3211841]], transfer learning schemes that port estimators across chemistries and vehicles [[10.1109/tpel.2021.3117788]][[10.1016/j.energy.2023.127033]], reinforcement learning agents for charging and prognostic model selection [[10.1016/j.ress.2025.111392]], and, most recently, large language model (LLM) agents for fleet-scale risk analysis and vehicle-cloud battery management [[10.1016/j.ress.2026.112416]][[10.1016/j.ensm.2026.104983]]."),

('h2', '1.3 Existing reviews and the literature gap'),
('p',
 "The review literature has grown alongside the applications, but it is fragmented along the same axes as the primary studies. Function-specific reviews cover SOC estimation [[10.1016/j.est.2022.104664]][[10.20517/jmi.2024.84]], SOH estimation [[10.1016/j.apenergy.2021.117346]], and prognostics [[10.1016/j.jechem.2023.03.026]] in depth, while method-specific reviews follow individual threads such as deep-learning state estimation [[10.1016/j.egyai.2025.100585]], physics-informed learning for impedance-based diagnostics [[10.1016/j.rser.2023.113807]], or interpretable ML for prognosis [[10.1002/aenm.202503067]]. Domain-anchored reviews examine fault diagnosis and safety [[10.3390/electronics10111309]][[10.1016/j.etran.2023.100254]] and thermal management [[10.1016/j.est.2023.106688]], alongside broader degradation-method surveys [[10.3390/batteries10070220]]. What is largely missing is a cross-functional, quantitative account of the field\u2019s trajectory: which method families are actually being used for which management tasks, on which data, validated how, and how that picture has shifted over the last five years."),

('p',
 "This gap matters because the field\u2019s self-image drives its research allocation. If, for example, most published health estimators are validated on within-cell splits of public datasets, the community\u2019s sense of progress is calibrated to a benchmark regime that differs sharply from fleet deployment. If interpretability claims are concentrated in a small method family, the safety case for certification-grade ML in production BMS is weaker than the volume of publications suggests. Answering such questions requires a corpus-level, cross-functional account of the field rather than another narrative synthesis of one function."),

('h2', '1.4 Contribution of this paper'),
('p',
 "This paper makes four contributions. First, it assembles a verified corpus of 103 peer-reviewed journal articles (2019\u20132026) on machine learning for battery management, in which every reference\u2019s bibliographic metadata was confirmed against the Crossref registry by direct DOI resolution. Second, it develops a two-axis classification framework \u2014 BMS function \u00d7 method family \u2014 extended with chemistry, data-source, and validation-practice fields, and applies it uniformly to all 103 papers. Third, it quantifies the field\u2019s five-year evolution across functions, methods, data, and validation (Section 3), identifying the shift from classical learners through deep sequence models to physics-informed hybrids, optimization-augmented learning, and early foundation-model applications. Fourth, it provides a critical, function-by-function review of what the corpus actually demonstrates (Sections 4\u20138) and distills a gap-driven research agenda (Section 9)."),

('p',
 "Fig. 1 previews the analysis, mapping the entire corpus across management functions and method families: the field\u2019s center of gravity sits squarely in the health-prognostics complex, hybrid model\u2013data approaches now span every function, and learning-based charging control remains a concentrated Bayesian-optimization stronghold. The remainder of the paper is organized as follows. Section 2 details the review methodology: search strategy, screening procedure, inclusion and exclusion criteria, and the classification framework, together with its limitations. Section 3 presents the corpus overview and five-year bibliometric analysis. Sections 4 through 7 review machine learning for state estimation, health estimation and prognostics, charging control, and thermal management, fault detection, and safety, respectively. Section 8 examines cross-cutting directions \u2014 physics-informed learning, interpretability and uncertainty, digital twins and cloud BMS, and foundation models. Section 9 formulates research gaps and future directions, and Section 10 concludes."),

('fig', 'figures/fig1_function_method_map.png', 'Fig. 1 The corpus mapped across battery-management functions and method families (91 primary-application papers; see Section 2.5 for terminology). Cell values are paper counts. The 12 corpus reviews are excluded here; the \u201cof which reviews\u201d column of Table 3 states the reconciliation directly, and no excluded review belongs to the physics-informed family, so that column\u2019s corpus total of 24 (Table 2) is unchanged.'),

('h1', '2. Review Methodology'),

('h2', '2.1 Scope and objective'),
('p',
 "The objective of this review is to characterize the current state and recent evolution of machine learning applied to battery management, understood as the set of estimation, protection, and control functions performed by or in support of a battery management system. The scope covers SOC estimation, SOH estimation and capacity tracking, remaining useful life (RUL) prediction and early-life prognosis, charging strategy optimization, thermal-state estimation and battery thermal management, fault diagnosis, anomaly detection and safety prediction, and cross-cutting methodological themes (physics-informed learning, transfer learning, interpretability, digital twins, cloud and fleet management, and foundation models). Battery *design* and *materials-discovery* applications of machine learning fall outside the scope except where they directly support a management function, such as manufacturing-quality prediction of cell capacity."),

('h2', '2.2 Literature search strategy'),
('p',
 "All candidate records were retrieved programmatically from the Crossref REST API between 4 and 5 September 2026 using 30 bibliographic query strings spanning the application areas listed above (for example, \u201cstate of charge estimation lithium-ion battery machine learning\u201d, \u201cremaining useful life prediction battery deep learning\u201d, \u201cphysics-informed neural network lithium-ion battery\u201d, and \u201clarge language model battery\u201d). Queries were issued in four passes: a top-cited pass over 2020\u20132026 sorted by citation count; a relevance-sorted recency pass restricted to mid-2024 onward; and two dedicated relevance-sorted passes restricted to 2020\u20132022 and to 2023, which together yielded 3,000 retrieved records. After DOI-based deduplication \u2014 1,450 duplicates removed \u2014 1,550 unique records remained. Six landmark studies \u2014 including the early-life prediction study [[10.1038/s41560-019-0356-8]] and the prognostics review [[10.1016/j.joule.2019.11.018]] \u2014 were additionally safeguarded as forced seeds: five were retrieved and verified individually because citation-sorted retrieval had crowded them out, and one was already among the top-cited hits."),

('p',
 "Two properties of this search design should be stated plainly. First, the Crossref registry is a metadata registry, not a discovery engine of the kind Scopus or Web of Science provide; it was chosen deliberately, because the aim of this review is that every included record be individually verifiable by direct DOI resolution, which registry-native retrieval guarantees and secondary databases cannot. The cost is a recall floor: coverage depends on Crossref registration, and the usual cross-database triangulation is absent. Second, the top-cited pass inherits the biases of citation counts \u2014 it favors established, English-language, high-profile work and mechanically over-weights older publications. The three remaining passes exist to counter exactly these biases, and all trend statements in this paper are statements about trends within this citation-weighted, English-language, journal-article sample rather than about the field in the aggregate."),

('h2', '2.3 Screening and selection procedure'),
('p',
 "The screening funnel is shown in Fig. 2. From 1,550 deduplicated records, a title-level relevance gate requiring both battery-related and machine-learning-related terminology retained 883 records and excluded 667 (predominantly adjacent-field papers \u2014 general machine-learning methods, adjacent-domain bibliometrics, and battery electrochemistry without a learning component \u2014 that surfaced through loose bibliographic matching). Venue and document-type screening then removed 84 records \u2014 conference abstracts and proceedings series (e.g., ECS Meeting Abstracts, IET/IFAC proceedings), preprint servers (SSRN), and non-scholarly venues \u2014 in line with the decision to restrict the corpus to peer-reviewed journal articles, leaving 799 eligible records. A function-quota selection step then drew 107 candidate articles from these, balancing the eight management functions and publication years; six landmark seed studies were confirmed or injected at this point (one already captured by the searches, five retrieved individually), giving 113 candidate articles. Full-text curation excluded 19 records \u2014 corrigenda, misindexed records, scope mismatches (for example, vehicle-level lifecycle assessment or charging-infrastructure demand modeling without a BMS function), and quota-driven trimming of over-represented function clusters \u2014 while 15 targeted additions were made from the screened pool for under-represented themes, a net change of \u22124 that yields the final corpus of 103 studies."),

('fig', 'figures/fig2_prisma.png', 'Fig. 2 Study-selection flowchart. Records were retrieved from the Crossref REST API on 4\u20135 September 2026, deduplicated, screened at title level for battery and machine-learning relevance, screened at venue and document-type level, and curated to the final 103-study corpus. Every included record\u2019s metadata was verified by direct DOI resolution against the Crossref registry.'),

('h2', '2.4 Inclusion and exclusion criteria'),
('p',
 "Table 1 summarizes the criteria. Inclusion required: (i) a peer-reviewed journal article; (ii) a battery or battery-system subject; (iii) machine learning as a substantive component of the contribution, whether estimation, control, diagnosis, or analysis; (iv) a publication year between 2019 and 2026, with 2019 admitted only for the field-defining early-life prediction study; and (v) English language. Exclusion criteria were: review-only papers without a primary application (admitted only into the cross-cutting cluster, capped at 12 studies), pure materials-discovery or cell-design papers, charging-infrastructure or grid-demand studies without an onboard management function, preprints and conference records, and duplicate-venue or misindexed records."),

('tbl', 'table1'),

('h2', '2.5 Classification framework'),
('p',
 "Each corpus paper was classified along six fields: (1) *management function*, with eight values \u2014 state estimation (SOC), health estimation (SOH), prognostics (RUL), charging control, thermal management, fault and safety, cell balancing and equivalent-circuit modeling, and a cross-cutting cluster for methodological and system-level themes; (2) *method family*, with values including classical ML (Gaussian process regression, support vector machines, random forests, shallow networks), deep learning (recurrent, convolutional, attention and graph architectures), physics-informed and hybrid model\u2013data learning, optimization-augmented learning (Bayesian optimization, surrogate-assisted and meta-heuristic schemes), reinforcement and control learning, transfer and domain adaptation, and foundation models/LLMs; (3) *chemistry* (NMC, LFP, LCO, lithium-metal, lithium\u2013sulfur, mixed, or unspecified); (4) *primary data source* (own laboratory cycling, public datasets, laboratory impedance spectroscopy, real vehicle or fleet data, simulation, or multiple sources); (5) *validation approach* (within-cell splits, cross-cell holdout, cross-chemistry or cross-domain transfer protocols, online/real-vehicle demonstration, experimental hardware, or simulation); and (6) a short coded summary of the headline finding and the principal limitation. Classification was performed by the lead author from registry-verified titles and abstracts, with conservative coding: where a paper\u2019s specifics could not be established confidently, broader categories were assigned. Three terms are used consistently hereafter: a *corpus paper* is any of the 103 included studies; a *primary study* (or *primary-application paper*) is one of the 91 whose contribution is a primary application rather than a review; and the 12 reviews are identified by the method-family field and are excluded from Fig. 1. Papers are assigned a single dominant value per field even where several apply. A co-author verification pass reviewed all 103 classifications, but because it was corrective rather than an independent blind double-coding, we report it as a checking pass and claim no inter-rater agreement statistic; the counts in Section 3 should accordingly be read as one documented coding of the corpus rather than as ground truth. The complete classified dataset is released with this paper precisely so that independent coders can check, correct, or extend it \u2014 and so that a formal reliability measurement can be run on the released labels."),

('h2', '2.6 Comparative synthesis approach'),
('p',
 "The synthesis proceeds on two tracks. Quantitatively, the classification fields are aggregated into cross-tabulations \u2014 function by year, method family by year, chemistry, data source, and validation practice \u2014 that characterize the corpus as a sample of the field\u2019s recent output (Section 3); every figure and every count in Section 3 was generated programmatically from the released dataset rather than compiled by hand; the full pipeline is publicly available in the repository accompanying this paper. Qualitatively, the review synthesizes each function\u2019s literature critically: what each cluster of methods assumes, what it demonstrates, and where its evidentiary support is thin (Sections 4\u20138). Cross-referencing the two tracks then yields the gap analysis of Section 9."),

('p',
 "The methodology has limitations that readers should weigh. The corpus is drawn from Crossref-registered journal articles and therefore inherits that registry\u2019s coverage: influential conference papers (a significant venue for control-oriented BMS work) are excluded by design, and very recent articles registered with incomplete metadata may evade relevance screening. Title-level relevance screening can miss relevant papers whose titles avoid standard terminology, and citation-count ranking privileges English-language, high-profile venues. The classification fields were assigned by a single coder; no inter-rater reliability statistic is available. These limitations qualify the quantitative aggregates of Section 3, which should be read as a structured sample of the field\u2019s output rather than a census \u2014 and they are the reason this paper describes itself as a scoping review with bibliometric classification rather than as a meta-analysis."),

('h1', '3. Corpus Overview and Five-Year Evolution'),

('h2', '3.1 Publication trend'),
('p',
 "The corpus spans 2019\u20132026 with a strongly increasing and then broadening profile: 9 papers in 2020, 13 in 2021, 13 in 2022, 22 in 2023, 20 in 2024, 18 in 2025, and 7 in the first half of 2026, plus the 2019 seed (Fig. 3). Two caveats apply to any reading of this trend. First, the corpus is a curated sample, not a census: it preferentially captures highly cited and recent work, so the shape of the curve partly reflects curation choices as well as field growth. Second, citation counts mechanically over-weight older publications; age-normalized, the post-2023 output is larger than the raw counts suggest. With those caveats, the profile is consistent with the field\u2019s bibliometric explosion after 2019\u20132020 and with a maturing phase in which incremental single-function estimators increasingly compete with cross-cutting system-level contributions."),

('p',
 "Citation weight tells a complementary story about influence. Citation counts throughout this paper are the Crossref registry\u2019s is-referenced-by-count values retrieved on 5 September 2026 and are included per paper in the released dataset; they are typically lower than Google Scholar counts for the same paper and should be compared only against themselves. The corpus accumulates roughly 18,400 recorded citations, but the distribution is steeply skewed: the median paper has 65 citations, while the 2019 seed alone holds 3,002 and the two 2020 landmark studies (Battery Lifetime Prognostics [[10.1016/j.joule.2019.11.018]] and closed-loop fast charging [[10.1038/s41586-020-1994-5]]) hold 1,239 and 1,078 respectively. Median citations fall monotonically with publication year \u2014 from 441 (2020) through 141 (2022) and 46 (2024) to single digits for 2026 publications \u2014 which is partly an age effect and partly evidence that the field\u2019s attention concentrates on a small set of canonical results. For a scoping review this skew matters: narrative reviews that emphasize highly cited work systematically describe the field as it stood in 2020\u20132021, whereas the recent relevance-sorted portions of this corpus capture the current working frontier that citations have not yet caught up with."),

('fig', 'figures/fig2_year_trend.png', 'Fig. 3 Corpus composition by publication year (bars, left axis) with cumulative total (line, right axis). The 2019 seed study is included in the cumulative count.'),

('h2', '3.2 Method-family evolution'),
('p',
 "The defining meta-finding of this review is the compositional shift in method families over the five-year window (Fig. 4, Table 2). Classical ML \u2014 Gaussian process regression, support vector machines, ensemble regressors, and shallow networks on engineered features \u2014 dominates the early corpus: 11 of the 23 papers published from 2019 through 2021. Deep sequence models (LSTM, GRU, CNN, attention and graph architectures) rise through 2022\u20132023 and remain the largest single family for prediction tasks thereafter. Physics-informed and hybrid model\u2013data learning \u2014 including physics-informed neural networks (PINNs), physics-constrained autoencoders, filter-embedded networks, and multiphysics-ML fusion \u2014 emerges in 2021\u20132022, grows steadily, and becomes the modal family by 2024\u20132026: counted year by year, the family contributes 1 paper in 2020, 2 in 2021, 3 in 2022, 4 in 2023, 5 in 2024, 4 in 2025, and 5 in 2026 \u2014 14 of its 24 corpus papers fall in 2024\u20132026, and it is the largest single component of the 7 papers published in 2026 (Table 2 gives the corpus-wide totals; Fig. 4 the yearly shares). Optimization-augmented learning (Bayesian optimization for protocol design, surrogate-assisted multi-objective schemes, and meta-heuristic-tuned networks) peaks in 2023\u20132024 (11 papers). Transfer and domain-adaptation approaches appear consistently from 2022 and accelerate in 2024\u20132025 (5 papers), reinforcement learning remains scarce but visible (1 corpus paper), and the first foundation-model and LLM-based studies appear in 2025\u20132026 (2 papers) [[10.1016/j.ress.2026.112416]][[10.1016/j.ensm.2026.104983]]."),

('tbl', 'TABLE_METH'),
('p',
 "Within-family dynamics deserve comment. The persistent classical-ML share is not inertia: Gaussian process regression survives because it natively returns calibrated uncertainty \u2014 the one property certification-minded applications cannot do without \u2014 and because feature-based estimators remain the cheapest to embed. The deep-learning share consolidated around recurrent and attention architectures for trajectory data and convolutional architectures for curve data, with graph networks appearing where cell-to-cell or feature-to-feature relations matter. The optimization-augmented family grew along two distinct branches: meta-heuristically tuned networks (PSO, GA, and swarm variants), which improve accuracy at a documented training cost, and Bayesian or surrogate-assisted optimization of *operating protocols*, which changes what can be experimentally discovered rather than merely what can be predicted. Conflating these two branches, as broad-brush surveys tend to do, obscures the more consequential of the two developments."),

('fig', 'figures/fig3_method_evolution.png', 'Fig. 4 Evolution of method-family shares in the corpus by publication year (share of papers published in each year). The 2019 seed (classical ML) is omitted for scale; families with fewer than two papers are pooled into their nearest parent family.'),

('p',
 "Three observations qualify this trajectory. First, the families are not mutually exclusive in practice \u2014 a PSO-tuned LSTM is simultaneously deep learning and optimization-augmented learning \u2014 and the corpus classification assigns each paper to its dominant family; the composition therefore understates method mixing. Second, the rise of physics-informed learning is partly a response to the recognized brittleness of purely data-driven models under distribution shift, but physics-informed papers in the corpus are, on average, validated no more stringently than others \u2014 if anything somewhat less stringently, a point quantified in Section 3.4. Third, the foundation-model cluster is too small to represent a trend; its significance is that LLM-based management (fleet risk analysis and vehicle-cloud orchestration) is appearing in mainstream energy journals at all."),

('h2', '3.3 Application-area distribution'),
('p',
 "Functionally, the corpus is dominated by the health-prognostics complex: health estimation (20 papers) and remaining-useful-life prognostics (15) together account for 34% of the 103-paper corpus, followed by the cross-cutting cluster (24, including reviews, physics-informed methods, interpretability, transfer learning, digital twins, cloud/fleet themes, and foundation models), state estimation (17), fault and safety (9), charging control (8), thermal management (8), and cell balancing/ECM (2) (Fig. 4). Fig. 5 matches the all-corpus totals of Table 3 (103 papers); Fig. 1, by contrast, is drawn over the 91-paper primary-application corpus and excludes the 12 reviews, with the per-function reconciliation stated in that figure\u2019s caption and in Table 3\u2019s \u201cof which reviews\u201d column. The concentration on SOH/RUL mirrors publication-volume patterns in the wider literature and reflects the strong commercial pull of lifetime prediction for warranties and second-life markets. By contrast, the thin representation of cell balancing is telling: balancing remains dominated by classical control practice, and ML has so far contributed mainly at the level of pack-level insight rather than as a balancing controller \u2014 the corpus\u2019s most-cited balancing-related result is the demonstration that routine balancing can be dispensed with in well-managed packs, reducing hazardous lithium-plating side reactions [[10.1016/j.est.2023.106931]]."),

('tbl', 'TABLE2'),
('p',
 "Chemistry and venue concentration complete the corpus profile. NMC-type cells anchor 53 of the 103 studies and LFP 15; the remainder split across LCO, lithium-metal, lithium\u2013sulfur, mixed panels, and unspecified chemistries \u2014 a distribution that mirrors EV market share but leaves sodium-ion, solid-state, and high-temperature systems nearly absent from the ML-management literature. Venue concentration is equally marked: the Journal of Energy Storage (14 papers), Energy (13), and Applied Energy (9) head the corpus, with Journal of Power Sources, Energy Storage Materials, and Reliability Engineering & System Safety following; IEEE transactions account for most of the remainder. The implication for readers is that the ML-BMS literature\u2019s center of gravity sits in energy-systems journals rather than in machine-learning venues \u2014 a sign that impact is currently demonstrated in application terms rather than in methodological novelty."),

('fig', 'figures/fig4_area_distribution.png', 'Fig. 5 Application-area distribution of the corpus. The cross-cutting cluster includes reviews, physics-informed learning, interpretability, transfer learning, digital twins, cloud and fleet management, and foundation models.'),

('h2', '3.4 Data landscape and validation practice'),
('p',
 "The data underpinning the corpus are strikingly concentrated (Fig. 6, Table 4). Thirty-six papers rely primarily on laboratory cycling of the authors\u2019 own cells; the public Severson/Toyota-MIT\u2013Stanford (MATR) cycle-life dataset alone supports 11 papers, NASA and CALCE datasets support 6 each, and laboratory impedance spectroscopy 6; 10 papers use real vehicle or fleet data as their primary data source \u2014 a distinct measure from the 9 studies whose *validation* is an online or real-vehicle demonstration (Section 3.4); 12 are simulation-based; and 15 are reviews or perspectives that synthesize rather than generate data. Chemistry reporting is similarly skewed: 53 papers work on NMC-based cells, 15 on LFP, and the remainder on LCO, lithium-metal, lithium\u2013sulfur, mixed panels, or unspecified chemistries."),

('p',
 "Validation practice \u2014 arguably the field\u2019s most consequential weakness \u2014 is summarized in Fig. 6 (right panel). Twenty-four papers validate on cross-cell holdout protocols, the most defensible laboratory standard; but 12 papers use within-cell splits (training and testing on interleaved segments of the same cell\u2019s life), 5 use k-fold cross-validation without cross-cell isolation, and 15 are reviews without primary validation. Only 9 studies validate a system online or on real vehicle/fleet data, and only 7 validate across chemistries. Because fleet-data *use* and online *validation* are different measures, Table 7 cross-tabulates them: of the 10 papers whose primary data are real-vehicle or fleet streams, 8 are online-validated and 2 are validated by transfer or case-study protocols instead; the 9th online-validated study uses laboratory data. This distribution quantifies a widely acknowledged but rarely measured problem: the majority of published accuracy claims are established under laboratory regimes that differ from deployment in chemistry coverage, temperature envelope, current-profile realism, and sensor quality \u2014 a gap that recurs throughout Sections 4\u20138."),

('fig', 'figures/fig5_data_validation.png', 'Fig. 6 Primary data sources (left) and validation approaches (right) across the corpus. Public-dataset reliance concentrates on the Severson/Toyota (MATR), NASA, and CALCE benchmarks; online or real-vehicle validation remains rare.'),

('tbl', 'TABLE_DATASETS'),
('p',
 "Validation practice deserves its own cross-tabulation because it moderates every accuracy claim in the corpus (Table 5). Cross-cell holdout \u2014 training on some cells and testing on unseen siblings \u2014 is the strongest widely used laboratory protocol (24 papers), and cross-chemistry or cross-domain transfer studies make the strictest demands (10 papers). At the weaker end, within-cell splits (12 papers) and unsupervised k-fold cross-validation (5 papers) leak trajectory information between train and test sets, producing optimistic errors that do not survive cell-to-cell variability; the review literature has long warned of this, and the corpus quantifies the warning. Experimental-hardware demonstrations (19 papers) and online or real-vehicle demonstrations (9 papers) anchor the strong end of the spectrum, and it is these \u2014 not the largest architectures \u2014 that carry the field\u2019s deployment evidence. Crossing validation practice with method family substantiates Section 3.2\u2019s remark with numbers: 13 of the 24 physics-informed/hybrid papers (54%) use one of the strong protocols, against 49 of the other 67 primary-application papers (73%) \u2014 a physics prior does not, in itself, buy validation rigor."),

('tbl', 'TABLE_VALID'),
('tbl', 'TABLE_FLEET'),
('p',
 "Reading Fig. 6 and Tables 4 and 5 together yields the section\u2019s headline: the field\u2019s data supply is narrow, and its validation habits are calibrated to that narrowness. Public benchmarks made cumulative progress possible \u2014 the Severson dataset alone catalyzed a family of early-prediction methods \u2014 but they now also cap the credibility of reported generalization. The studies that escape this trap are precisely those that treat data sourcing and validation design as the research contribution: the multi-cell pipeline studies, the fleet-data health estimators, and the transfer-learning frameworks."),

('p',
 "The concentration can be stated as a metric. Across 2019\u20132026, 23 corpus papers \u2014 more than a fifth of the primary-application corpus \u2014 rest on the same three public benchmarks (MATR, NASA, CALCE; Fig. 7). Because these benchmarks together contain on the order of a few hundred cells, the field\u2019s effective empirical sample has grown far more slowly than its publication count: output rose from single digits per year in 2019\u20132020 to 15\u201320 papers per year by 2023\u20132025, while benchmark-reuse kept pace step for step. We call this pattern benchmark saturation: the empirical base on which the community calibrates and compares estimators is approximately fixed while the literature multiplies on top of it, which inflates apparent comparability and hides dataset-specific failure modes."),

('fig', 'figures/fig7_dataset_saturation.png', 'Fig. 7 Benchmark saturation. Papers using the three dominant public benchmarks per year (stacked bars, left axis) against total corpus output per year (line, right axis). Benchmark reuse tracks publication growth throughout the window: the empirical base does not broaden as the literature multiplies.'),

('h2', '3.5 Sensitivity analysis: does the journal-only corpus understate validation practice?'),

('p',
 "Because the corpus excludes conference proceedings \u2014 a major venue for control-oriented BMS work (CDC, ACC, IFAC, VPPC, ITEC) \u2014 the validation findings of Section 3.4 could in principle be an artifact of venue selection: if conference papers systematically demonstrate more hardware and hardware-in-the-loop validation than journals, the journal-only sample would understate the field\u2019s actual practice. To test this, we curated a sensitivity set of 14 machine-learning battery papers from six control and transportation-electrification venues (ACC, ECC, CCDC, APEC, VPPC, ITEC, 2019\u20132025), retrieved by venue-scoped Crossref queries, restricted to proceedings articles, ranked by citation count, and verified by the same DOI-resolution procedure as the main corpus (released as conference_sensitivity.csv). Validation practice was classified conservatively from the indexed abstracts by keyword screening into four classes: hardware/experimental stated, public dataset, simulation-level, and not stated."),

('tbl', 'TABLE_CONF'),

('p',
 "The result supports representativeness rather than a venue gap. Only 2 of the 14 conference papers (14%) state hardware or experimental validation in their indexed abstracts, 2 rest on public datasets, and 4 describe simulation-level validation \u2014 against 19 of the 91 primary-application journal papers (21%) with experimental-hardware demonstrations and a 68% strong-protocol share (Table 5). Indexed abstract-level transparency about validation is, if anything, lower on the conference path, with 5 of 14 abstracts stating no validation basis at all. Two caveats bound this finding: conference abstracts are frequently truncated in bibliographic indexes, so the comparison measures stated evidence rather than underlying practice; and the sensitivity set is a curated sample, not a census. Within those bounds, however, the journal-only corpus does not understate the field\u2019s validation transparency \u2014 and the observation that neither venue type reports validation systematically strengthens, rather than weakens, the case for the reporting standards proposed in Section 9.7."),
]