#!/usr/bin/env python3
"""Condensed TTE-submission text (12-page limit): part 2."""

BLOCKS = [
('h1', '3. Corpus Overview and Five-Year Evolution'),

('h2', '3.1 Publication trend and method-family evolution'),
('p',
 "The corpus spans 2019\u20132026 (9, 13, 13, 22, 20, 18, and 7 papers per year from 2020 onward, plus the 2019 seed; Fig. 3), subject to the caveats that it is a curated sample favoring highly cited and recent work and that citation counts over-weight older publications. The defining meta-finding is the compositional shift in method families (Fig. 3, Table I). Classical ML \u2014 Gaussian process regression, support vector machines, ensembles, and shallow networks on engineered features \u2014 contributes 11 of the 23 papers published from 2019 through 2021. Deep sequence models rise through 2022\u20132023 and remain the largest family for prediction tasks. Physics-informed and hybrid model\u2013data learning becomes the modal family by 2024\u20132026: counted year by year, it contributes 1, 2, 3, 4, 5, 4, and 5 papers \u2014 14 of its 24 corpus papers fall in 2024\u20132026, and it is the largest component of the 7 papers published in 2026 (Table II gives corpus-wide totals). Optimization-augmented learning (Bayesian optimization, surrogate-assisted and meta-heuristic schemes) peaks in 2023\u20132024 (11 papers); transfer learning accelerates in 2024\u20132025 (5 papers); reinforcement learning remains scarce but visible (1 corpus paper); and the first foundation-model and LLM-based studies appear in 2025\u20132026 (2 papers) [[10.1016/j.ress.2026.112416]][[10.1016/j.ensm.2026.104983]]. Two qualifications matter: the families are not mutually exclusive (a PSO-tuned LSTM is both deep learning and optimization-augmented), so the composition understates method mixing; and physics-informed papers are, on average, validated no more stringently than others \u2014 if anything somewhat less stringently, a point quantified in Section 3.4."),

('fig', 'figures/fig3_method_evolution.png', 'Fig. 3 Evolution of method-family shares in the corpus by publication year. The 2019 seed (classical ML) is omitted for scale.'),

('tbl', 'TABLE_METH'),

('h2', '3.2 Application-area distribution'),
('p',
 "Functionally, the corpus is dominated by the health-prognostics complex: health estimation (20 papers) and remaining-useful-life prognostics (15) together account for 34% of the 103-paper corpus, followed by the cross-cutting cluster (24), state estimation (17), fault and safety (9), charging control (8), thermal management (8), and cell balancing (2) (Fig. 1; Table III gives the composition by year, with the review reconciliation; Table IV maps representative studies across all functions). This concentration mirrors publication-volume patterns in the wider literature and the commercial pull of lifetime prediction for warranties and second-life markets. The thin representation of cell balancing is telling: balancing remains dominated by classical control practice, and the corpus's most-cited balancing-related result is the demonstration that routine balancing can be dispensed with in well-managed packs, reducing hazardous lithium-plating side reactions [[10.1016/j.est.2023.106931]]. Venue concentration is equally marked \u2014 the Journal of Energy Storage (14 papers), Energy (13), and Applied Energy (9) head the corpus \u2014 a sign that impact is currently demonstrated in application terms rather than in methodological novelty."),

('tbl', 'TABLE2'),

('h2', '3.3 Data landscape and validation practice'),
('p',
 "The data underpinning the corpus are strikingly concentrated: 36 papers rest on laboratory cycling of the authors' own cells; the public Severson/Toyota\u2013MIT\u2013Stanford (MATR) dataset alone supports 11, NASA and CALCE 6 each, and laboratory impedance spectroscopy 6; 10 papers use real vehicle or fleet data as their primary source \u2014 distinct from the 9 studies whose validation is an online or real-vehicle demonstration (Table V); 12 are simulation-based; and 15 are reviews or perspectives. Chemistry reporting is similarly skewed: 53 papers work on NMC-based cells and 15 on LFP, leaving sodium-ion, solid-state, and high-temperature systems nearly absent from the ML-management literature. Validation practice is arguably the field's most consequential weakness. Cross-cell holdout \u2014 the strongest common laboratory protocol \u2014 accounts for 24 papers, and cross-chemistry or cross-domain transfer studies for 10; but within-cell splits (12 papers) and unsupervised k-fold cross-validation (5) leak trajectory information between train and test, producing optimistic errors that do not survive cell-to-cell variability. Only 9 studies validate a system online or on fleet data, and only 7 validate across chemistries. Crossing validation practice with method family substantiates the remark in Section 3.1 with numbers: 13 of the 24 physics-informed/hybrid papers (54%) use one of the strong protocols, against 49 of the other 67 primary-application papers (73%) \u2014 a physics prior does not, in itself, buy validation rigor."),


('p',
 "The benchmark concentration can be stated as a metric (Fig. 4). Across 2019\u20132026, 23 corpus papers \u2014 more than a fifth of the primary-application corpus \u2014 rest on the same three public benchmarks. Because these benchmarks together contain on the order of a few hundred cells, the field's effective empirical sample has grown far more slowly than its publication count: output rose from single digits per year in 2019\u20132020 to 15\u201320 papers per year by 2023\u20132025, while benchmark reuse kept pace step for step. We call this pattern benchmark saturation: the empirical base on which the community calibrates and compares estimators is approximately fixed while the literature multiplies on top of it, inflating apparent comparability and hiding dataset-specific failure modes."),

('fig', 'figures/fig7_dataset_saturation.png', 'Fig. 4 Benchmark saturation. Papers using the three dominant public benchmarks per year (stacked bars, left axis) against total corpus output per year (line, right axis).'),


('h2', '3.4 Sensitivity analysis: does the journal-only corpus understate validation practice?'),
('p',
 "Because the corpus excludes conference proceedings \u2014 a major venue for control-oriented BMS work (CDC, ACC, IFAC, VPPC, ITEC) \u2014 the validation findings could in principle be a venue-selection artifact. To test this, we curated a sensitivity set of 14 machine-learning battery papers from six control and transportation-electrification venues (2019\u20132025), retrieved by venue-scoped Crossref queries, restricted to proceedings articles, ranked by citation count, and verified by the same DOI-resolution procedure as the main corpus (released as conference_sensitivity.csv). Validation practice was classified conservatively from the indexed abstracts (Table III). The result supports representativeness rather than a venue gap: only 2 of the 14 conference papers (14%) state hardware or experimental validation in their indexed abstracts, 2 rest on public datasets, and 4 describe simulation-level validation \u2014 against 19 of the 91 primary-application journal papers (21%) with experimental-hardware demonstrations and a 68% strong-protocol share. Abstract-level transparency about validation is, if anything, lower on the conference path. Two caveats bound this finding: conference abstracts are frequently truncated in bibliographic indexes, so the comparison measures stated evidence rather than underlying practice; and the set is a curated sample, not a census. Within those bounds, the journal-only corpus does not understate the field's validation transparency \u2014 and neither venue type reports validation systematically, which strengthens the case for the reporting standards proposed in Section 9."),

('tbl', 'TABLE_CONF'),

('h1', '4. Machine Learning for Battery State Estimation'),
('p',
 "SOC estimation is the most mature BMS function, and the corpus shows how machine learning entered it. The early pattern pairs learning with classical estimation: Gaussian process regression for pack-level SOC with native uncertainty quantification [[10.1016/j.energy.2020.118000]], and \u2014 most influentially \u2014 recurrent networks embedded in unscented Kalman filters, where the LSTM supplies a learned observation model and the filter recursive correction [[10.1016/j.energy.2020.117664]]. A second generation tuned network structure itself: particle-swarm-optimized LSTM improved accuracy and noise robustness [[10.1016/j.energy.2021.121236]], and evolutionary-assisted CNN\u2013BiLSTM hybrids report sub-1% drive-cycle errors [[10.1016/j.heliyon.2024.e35183]]. Simulation-informed training pipelines substitute automotive-accurate simulated data for exhaustive cell testing [[10.1016/j.jpowsour.2020.229108]], comparative benchmarks on standard drive cycles weigh ML regression families [[10.3390/wevj12010038]], pack heterogeneity is addressed by joint pack-SOC and cell-inconsistency estimation with balancing-aware formulations [[10.1109/access.2021.3068776]], and unified frameworks estimate SOH and SOC jointly from partial charging data [[10.1016/j.ensm.2022.06.053]], and large-format applications extend estimation to containerized storage strings [[10.1016/j.jpowsour.2024.235609]], with comparative benchmarks weighing accuracy against embedded compute budgets [[10.1016/j.est.2024.114281]][[10.1016/j.est.2024.111877]]."),
('p',
 "The most substantive recent shift is toward hybrid schemes in which a filter, an equivalent-circuit model, or a physics prior constrains the learner: GA-optimized LSTM coupled with improved adaptive Kalman filtering reaches low error under measurement noise that breaks pure-network estimators [[10.1016/j.apenergy.2024.123508]]; equivalent-circuit-informed ML on impedance features estimates SOC across temperatures [[10.1016/j.energy.2023.128461]]; and physics-informed recurrent structures embed battery dynamics directly into the training objective [[10.1109/jrfid.2022.3211841]]. These schemes trade engineering complexity for extrapolation behavior \u2014 the property that matters most onboard. Yet 13 of the 17 corpus SOC papers rest on laboratory-scale data and 12 on a single chemistry, and only one demonstrates fleet-scale operation [[10.1016/j.jpowsour.2024.235609]]; benchmark heterogeneity makes cross-paper comparison nearly meaningless [[10.1016/j.egyai.2025.100585]][[10.20517/jmi.2024.84]]. The laboratory problem is largely solved; the deployment problem \u2014 guaranteed accuracy on arbitrary packs over full aging \u2014 is not."),

('h1', '5. Machine Learning for Health Estimation and Prognostics'),
('p',
 "SOH estimation and RUL prediction form the largest functional block of the corpus (35 papers). The founding pattern is classical: extract health-sensitive features from partial charge or discharge curves, then regress with Gaussian process or similar shallow models \u2014 incremental-capacity analysis with explicit uncertainty bounds [[10.1016/j.energy.2019.116467]], differential thermal voltammetry [[10.1109/tte.2020.3028784]], and Gaussian-process classification of impedance spectra that identifies degradation modes [[10.1038/s41467-020-15235-7]], and deep Gaussian processes coupling prognosis with degradation-mode identification [[10.1016/j.jpowsour.2019.227281]]. Measurement relaxations followed: random partial charging data proved sufficient for accurate SOH [[10.1109/tpel.2021.3134701]], and charging-segment adjustment refined features for vehicle-level use [[10.1016/j.apenergy.2024.124077]]. The landmark systematization is Roman et al.'s 179-cell pipeline showing that relaxed charge-curve features support accurate SOH estimation across a heterogeneous commercial fleet [[10.1038/s42256-021-00312-3]]."),
('p',
 "Deep architectures entered as sequence models over capacity-fade trajectories and representation learners over raw curves: graph convolutional networks fusing multiple health indicators [[10.1016/j.ress.2022.108947]], graph networks over partial discharge curves [[10.1016/j.est.2024.113502]], BiLSTM\u2013Transformer hybrids under fast-charging stress [[10.1016/j.energy.2024.133418]], hybrid-fusion networks for real-time prediction streams [[10.1016/j.energy.2025.136618]], and interpretable deep learning with transparency mechanisms [[10.1016/j.apenergy.2024.124713]]. Field-data studies absorb real-vehicle noise [[10.1016/j.energy.2023.126855]] and estimate pack-level SOH from fleet streams [[10.1016/j.geits.2024.100169]], while deep models estimate SOH without additional degradation experiments by learning trajectory features that generalize across chemistries [[10.1038/s41467-023-38458-w]]. Early-life prediction \u2014 forecasting lifetime from the first cycles \u2014 compresses test times from months to days [[10.1038/s41560-019-0356-8]][[10.1016/j.apenergy.2021.116897]][[10.1016/j.energy.2021.120205]], hybrid physics-plus-learned models give early RUL from limited cycles [[10.1016/j.jclepro.2021.128265]], extends to lithium-metal chemistries [[10.1002/advs.202402608]], and now runs on embedded boards in real time [[10.1016/j.est.2022.104901]]."),
('p',
 "The prognostics cluster shows the clearest physics-informed turn: physics-informed online degradation models [[10.1016/j.ymssp.2022.109347]], hybrid reinforcement learning that reduces the data demand of SOH estimation [[10.1038/s41598-025-30602-4]], a generalizable PINN from limited early-cycle data [[10.1016/j.jechem.2025.08.093]], EIS-informed physics-constrained networks [[10.1016/j.energy.2025.139753]], a generic physics-informed RUL framework for small early-life samples [[10.1016/j.apenergy.2025.125314]], multi-feature hybrids across datasets [[10.1016/j.est.2025.118415]], recurrent networks anticipating uncertain duty [[10.1016/j.ensm.2022.05.007]], and signal-decomposition hybrids on noisy capacity series [[10.1038/s41598-025-92262-8]]. Transfer learning attacks generalization directly: domain-adversarial training across operating conditions [[10.1109/tpel.2021.3117788]], deep transfer with partial charging curves across cell types [[10.1016/j.energy.2023.127033]], transfer under fast-charging protocols [[10.1016/j.isci.2025.112235]], cross-chemistry EIS estimation [[10.1109/tte.2025.3533540]], and a general framework quantifying the laboratory-to-fleet domain gap [[10.1016/j.apenergy.2024.125086]]. The critical assessment: accuracy claims cluster around 1\u20132% SOH error, but they are established overwhelmingly on public benchmark cells \u2014 10 of the 35 studies in this complex use within-cell or k-fold validation (17 corpus-wide) \u2014 and the transfer-learning papers, the honest exception, reveal how much shift remains unaddressed. SOH estimation under controlled conditions is approaching incremental returns; calibrated lifetime and safety margins for arbitrary packs in the field remain open [[10.1016/j.joule.2019.11.018]][[10.1016/j.jechem.2023.03.026]]."),

('tbl', 'TABLE_REP'),

('h1', '6. Machine Learning for Charging Control and Optimization'),
('p',
 "Charging control is the function where machine learning has changed experimental practice most directly. The defining result is Attia et al.: a Bayesian optimization loop identified fast-charging protocols within 2.5 months, against roughly 18 months of manual search [[10.1038/s41586-020-1994-5]]. Ensemble surrogates make multi-objective strategy optimization tractable [[10.1016/j.enconman.2025.120170]], and Bayesian fast-charging optimization reduces charge time under degradation constraints [[10.1109/tte.2023.3311813]]. A second line embeds degradation mechanisms into the decision itself: machine-learning fast charging that perceives and regulates internal lithium-plating onset enables plating-free rapid protocols [[10.1016/j.ensm.2022.12.034]], adaptive multistage schemes adjust stage boundaries against measured degradation [[10.1016/j.renene.2019.08.077]], module-level optimization manages temperature gradients [[10.1016/j.energy.2022.126331]], and pack-level extensions coordinate balance-aware charging [[10.1016/j.est.2024.111755]][[10.1016/j.est.2024.112046]]."),
('p',
 "The deployment gap is most concrete here: of the eight charging papers, one is a large-scale closed-loop hardware campaign, three validate on laboratory hardware, and the rest are simulation-only. The unsolved problem is certifiable learning-based charging \u2014 which is why mechanism-aware schemes such as plating-perception control [[10.1016/j.ensm.2022.12.034]] are the cluster's most deployment-relevant results."),

('h1', '7. Machine Learning for Thermal Management, Faults and Safety'),
('p',
 "Thermal management (8 papers) divides by purpose. For estimation, ANN models predict cell temperature across operating conditions [[10.1016/j.applthermaleng.2023.120482]] and internal-temperature sensing extends to ultrahigh-rate discharge where surface measurement fails [[10.1016/j.apenergy.2026.127394]]. For design, ML surrogates amortize expensive CFD evaluation across optimization loops [[10.1016/j.jpowsour.2021.229727]][[10.1016/j.applthermaleng.2024.123826]], with experimentally validated parallel-liquid-cooling designs closing the loop [[10.1016/j.applthermaleng.2022.118503]]. For control, ANN controllers demonstrate parasitic-load reductions in simulation [[10.3390/wevj16050279]] \u2014 but no corpus paper closes this loop on hardware, leaving thermal control where charging control was five years ago. Physics-informed heat-generation estimation embeds thermal priors into the learning problem [[10.1016/j.jechem.2022.11.036]], and the cluster is consolidated by a state-of-the-art review [[10.1016/j.est.2023.106688]]."),
('p',
 "Fault and safety applications (9 papers) divide into diagnosis of realized faults and prediction of impending hazards: grid-search-optimized SVMs classify sensor and connection faults [[10.1016/j.energy.2020.118866]], curvilinear-distance methods detect multiple pack fault types in operating fleets [[10.1016/j.est.2023.107575]], and multi-scenario deep anomaly detection covers real EV operating envelopes [[10.1016/j.etran.2025.100418]]; force-signal deep learning catches lithium-plating-type defects at manufacturing [[10.1016/j.jechem.2025.04.025]]. The hazard-prediction side is increasingly model-based: multiphysics models coupled with ML predict module-level thermal-runaway progression [[10.1016/j.jpowsour.2024.235015]], a multiphysics-informed DeepONet augments scarce experimental events with virtual data [[10.1016/j.etran.2024.100337]], and multi-source domain transfer moves thermal-runaway diagnosis across fleets with small target samples [[10.1016/j.apenergy.2024.123248]]. The reviews in this cluster are candid that laboratory fault diagnosis has historically failed to transfer to real vehicles [[10.1016/j.etran.2023.100254]][[10.3390/electronics10111309]]; the fleet-data anomaly-detection studies are therefore the cluster's most valuable trend, even though label scarcity for rare faults keeps evaluation largely qualitative."),

]
