#!/usr/bin/env python3
"""Condensed TTE-submission text (12-page limit): part 1.
Citation coverage mirrors the full manuscript; prose tightened."""

TITLE = "Machine learning in battery management systems: a structured scoping review and classification of 103 peer-reviewed studies, 2019\u20132026"

AUTHOR_LINES = [("Hussain Touhid Siddiquee", "Leading University, Sylhet, Bangladesh"),
                ("Syeda Salsabil Islam Ariya", "Leading University, Sylhet, Bangladesh"),
                ("Jasimul Islam Chowdhury", "Leading University, Sylhet, Bangladesh")]

ABSTRACT = [
 "Machine learning (ML) has moved from a promising addition to battery research to a load-bearing component of modern battery management systems (BMS), yet the validation practices behind the literature's accuracy claims have never been systematically measured. This paper presents a structured scoping review of 103 peer-reviewed journal articles (2019\u20132026) \u2014 assembled from a Crossref-verified pool and classified uniformly by management function, method family, chemistry, data source, and validation practice \u2014 supported by a 14-paper conference sensitivity set. The bibliometric analysis reveals a clear evolution: classical shallow learners dominated 2019\u20132021, deep sequence models rose sharply in 2022\u20132023, physics-informed and hybrid model\u2013data approaches became one of the fastest-growing families (24 of 103 papers), and the first large-language-model-based management studies appear in 2025\u20132026. Health estimation and prognostics remain the largest application cluster (35 papers). Three structural weaknesses persist. Only 9 of 103 studies demonstrate online or fleet-level operation, while 17 rely on within-cell or k-fold splits that overstate generalization; benchmark reliance is narrow, with 23 papers resting on three public datasets; and the laboratory-to-field gap remains the field's defining challenge. The review's sharpest finding is that physics-informed architectures, often assumed to improve reliability by construction, are validated less rigorously than purely data-driven peers (54% versus 73% strong-protocol share): physics priors reduce data demand but do not substitute for rigorous out-of-distribution testing. The paper closes with a conference-path sensitivity analysis, a safety taxonomy for foundation-model components, and BMS-ML-RC, a twelve-item CONSORT-style reporting checklist for future machine-learning BMS studies.",
]

KEYWORDS = ("machine learning; battery management systems; lithium-ion batteries; state of charge; "
            "state of health; remaining useful life; deep learning; physics-informed neural networks; "
            "transfer learning; battery safety")

BLOCKS = [
('h1', '1. Introduction'),

('h2', '1.1 The battery management problem'),
('p',
 "Lithium-ion batteries now anchor three converging transitions \u2014 electrified road transport, renewable-heavy stationary storage, and the electrification of aerospace and marine systems \u2014 and in each the battery is an actively managed asset whose usable capacity, lifetime, and safety depend on real-time operating decisions. The battery management system (BMS) is the embedded cyber-physical layer that makes those decisions — sensing, state estimation, protection, balancing, and charging negotiation [[10.1038/s42256-020-0156-7]]. The difficulty stems from the fact that the quantities that matter most \u2014 state of charge (SOC), state of health (SOH), internal temperature, and the onset of degradation or fault mechanisms \u2014 are not directly measurable and must be inferred from noisy, partially observable terminal measurements under widely varying conditions. Model-based approaches built on equivalent-circuit or electrochemical models face a persistent fidelity-versus-tractability trade-off, and their parameters drift as cells age [[10.1016/j.joule.2019.11.018]]. It is in this inference-and-decision layer that machine learning has made its most forceful entry."),

('p',
 "Machine learning entered battery management through estimation on hand-engineered features. Two studies then reset expectations. Severson and colleagues predicted the entire cycle life of lithium-ion cells with a median test error near 9% from the first hundred cycles alone, on a public dataset of 124 cells [[10.1038/s41560-019-0356-8]]. Attia and colleagues demonstrated closed-loop Bayesian optimization of fast-charging protocols in 2.5 months rather than 18 months of manual experimentation [[10.1038/s41586-020-1994-5]]. The five years that followed produced applications across every BMS function: recurrent and convolutional networks for SOC and SOH [[10.1016/j.energy.2020.117664]][[10.1016/j.energy.2023.126855]], graph and transformer architectures for prognostics [[10.1016/j.ress.2022.108947]][[10.1016/j.energy.2024.133418]], physics-informed neural networks embedding electrochemical and thermal priors [[10.1016/j.jechem.2022.11.036]][[10.1109/jrfid.2022.3211841]], transfer learning across chemistries and vehicles [[10.1109/tpel.2021.3117788]][[10.1016/j.energy.2023.127033]], reinforcement learning agents [[10.1016/j.ress.2025.111392]], and, most recently, large language model (LLM) agents for fleet-scale risk analysis and vehicle-cloud management [[10.1016/j.ress.2026.112416]][[10.1016/j.ensm.2026.104983]]."),

('h2', '1.2 Existing reviews and the literature gap'),
('p',
 "The review literature has grown alongside the applications but is fragmented along the same axes as the primary studies: function-specific reviews cover SOC estimation [[10.1016/j.est.2022.104664]][[10.20517/jmi.2024.84]], SOH estimation [[10.1016/j.apenergy.2021.117346]], and prognostics [[10.1016/j.jechem.2023.03.026]]; method-specific reviews follow deep-learning state estimation [[10.1016/j.egyai.2025.100585]], physics-informed impedance diagnostics [[10.1016/j.rser.2023.113807]], or interpretable prognosis [[10.1002/aenm.202503067]]; and domain reviews examine fault diagnosis [[10.3390/electronics10111309]][[10.1016/j.etran.2023.100254]] and thermal management [[10.1016/j.est.2023.106688]], alongside broader degradation-method surveys [[10.3390/batteries10070220]]. What is missing is a cross-functional account of the field's trajectory: which method families are used for which tasks, on which data, validated how. Answering this requires a corpus-level account rather than another narrative synthesis of one function."),

('h2', '1.3 Contribution of this paper'),
('p',
 "This paper makes four contributions: a verified corpus of 103 peer-reviewed studies (2019\u20132026) with every reference confirmed against the Crossref registry by DOI resolution; a two-axis classification framework (BMS function \u00d7 method family) extended with chemistry, data-source, and validation-practice fields; a quantified five-year evolution (Section 3); and a function-by-function critical review (Sections 4\u20138) with a conference-path sensitivity analysis and a gap-driven agenda including a reporting checklist (Section 9). Fig. 1 previews the analysis, mapping the entire corpus across management functions and method families: the field's center of gravity sits in the health-prognostics complex, hybrid model\u2013data approaches now span every function, and learning-based charging control remains a concentrated Bayesian-optimization stronghold. The remainder of the paper is organized as follows. Section 2 details the review methodology and its limitations. Section 3 presents the corpus overview and five-year bibliometric analysis. Sections 4 through 7 review machine learning for state estimation, health estimation and prognostics, charging control, and thermal management, fault detection, and safety. Section 8 examines cross-cutting directions, and Sections 9 and 10 give the research agenda and conclusions."),

('fig', 'figures/fig1_function_method_map.png', 'Fig. 1 The corpus mapped across battery-management functions and method families (91 primary-application papers; the 12 corpus reviews are excluded). The \u201cof which reviews\u201d column of Table II states the reconciliation directly; no excluded review belongs to the physics-informed family, so that column\u2019s corpus total of 24 (Table I) is unchanged.'),

('h1', '2. Review Methodology'),

('h2', '2.1 Search strategy'),
('p',
 "All candidate records were retrieved programmatically from the Crossref REST API between 4 and 5 September 2026 using 30 bibliographic query strings spanning the application areas above. Queries were issued in four passes (top-cited 2020\u20132026; recency from mid-2024; dedicated 2020\u20132022 and 2023 windows), yielding 3,000 records; after DOI-based deduplication (1,450 duplicates removed), 1,550 unique records remained. Six landmark studies \u2014 including [[10.1038/s41560-019-0356-8]] and [[10.1016/j.joule.2019.11.018]] \u2014 were additionally safeguarded as forced seeds: five were retrieved and verified individually because citation-sorted retrieval had crowded them out, and one was already among the top-cited hits. Two properties should be stated plainly. The Crossref registry is a metadata registry, not a discovery engine like Scopus or Web of Science; it was chosen deliberately so that every included record is individually verifiable by direct DOI resolution, at the cost of a recall floor and no cross-database triangulation. Citation-count ordering also favors established, English-language work; the recency passes counter this bias, and all trend statements describe this citation-weighted, English-language, journal-article sample rather than the field in the aggregate."),

('h2', '2.2 Screening and selection'),
('p',
 "The screening funnel is shown in Fig. 2. A title-level relevance gate requiring both battery-related and machine-learning terminology retained 883 records and excluded 667 (predominantly adjacent-field papers that surfaced through loose matching). Venue and document-type screening removed 84 records \u2014 conference abstracts and proceedings series, preprint servers, and non-scholarly venues \u2014 leaving 799 eligible records. A function-quota selection step drew 107 candidate articles balanced across the eight management functions and publication years; six landmark seeds were confirmed or injected (one already captured, five retrieved individually), giving 113 candidates. Full-text curation excluded 19 records (corrigenda, misindexed records, scope mismatches, and quota-driven trimming of over-represented clusters) while 15 targeted additions were made from the screened pool for under-represented themes \u2014 a net \u22124 that yields the final corpus of 103 studies. Inclusion required a peer-reviewed journal article on a battery subject with machine learning as a substantive component (2020\u20132026, plus one 2019 field-defining seed), verified by direct Crossref DOI resolution; review-only papers were admitted only into the cross-cutting cluster, capped at 12 studies."),

('fig', 'figures/fig2_prisma.png', 'Fig. 2 Study-selection flowchart. Records were retrieved from the Crossref REST API on 4\u20135 September 2026, deduplicated, screened at title level for battery and machine-learning relevance, screened at venue and document-type level, and curated to the final 103-study corpus.'),

('h2', '2.3 Classification framework and limitations'),
('p',
 "Each paper was classified along six fields: management function (eight values, including a cross-cutting cluster); dominant method family (classical ML, deep learning, physics-informed/hybrid, optimization-augmented, reinforcement/control learning, transfer learning, foundation models/LLMs, review); chemistry; primary data source; validation approach; and a coded summary of the headline finding and principal limitation. Three terms are used consistently: a *corpus paper* is any of the 103 included studies; a *primary study* (or *primary-application paper*) is one of the 91 whose contribution is a primary application rather than a review. Classification was performed by the lead author with conservative coding; a co-author verification pass reviewed all 103 classifications, but because it was corrective rather than an independent blind double-coding, we claim no inter-rater agreement statistic \u2014 the counts in Section 3 should be read as one documented coding of the corpus, and the complete dataset is released so that independent coders can check or extend it. The synthesis proceeds on two tracks: quantitative cross-tabulations generated programmatically from the released dataset (Section 3), and qualitative function-by-function critique (Sections 4\u20138). The methodology's limitations are acknowledged: Crossref coverage excludes influential conference papers; title-level screening can miss relevant work; citation ranking privileges high-profile venues; and no formal reliability statistic is available. These are the reasons this paper describes itself as a scoping review with bibliometric classification rather than a meta-analysis."),
]
